// import the library
import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faCode,
  faHighlighter,
  faTools,
  faHome,
  faPowerOff,
  faQuestion,
  faQuestionCircle,
  faUsers,
  faFolder,
  faBuilding,
  faUserTie,
  faUserCircle,
  faTasks,
  faAngleUp,
  faAngleDown,
  faArrowRight,
  faArrowLeft,
  faLongArrowAltLeft,
  faLongArrowAltRight,
  faSearch,
  faPhone,
  faPhoneAlt,
  faPhoneSquare,
  faEdit,
  faTrash,
  faMapMarkerAlt,
  faTh,
  faList,
  faBars,
  faTimes,
  faEllipsisV,
  faGripHorizontal,
  faThLarge,
  faGripLines,
  faUserAlt,
  faPlus,
  faCheck,
  faCheckCircle,
  faCog,
  faUser,
} from "@fortawesome/free-solid-svg-icons";

import { faQuestionCircle as faQuestionCircleRegular } from "@fortawesome/free-regular-svg-icons";

export default function registerIcons() {
  library.add(
    faCode,
    faHighlighter,
    faTools,
    faHome,
    faPowerOff,
    faQuestion,
    faQuestionCircle,
    faQuestionCircleRegular,
    faUsers,
    faUserCircle,
    faFolder,
    faBuilding,
    faUserTie,
    faTasks,
    faAngleUp,
    faAngleDown,
    faArrowRight,
    faArrowLeft,
    faLongArrowAltLeft,
    faLongArrowAltRight,
    faSearch,
    faPhone,
    faPhoneAlt,
    faPhoneSquare,
    faEdit,
    faTrash,
    faMapMarkerAlt,
    faPhoneAlt,
    faTh,
    faList,
    faBars,
    faTimes,
    faEllipsisV,
    faGripHorizontal,
    faThLarge,
    faGripLines,
    faUserTie,
    faUserAlt,
    faPlus,
    faCheck,
    faCheckCircle,
    faCog,
    faUser

    // more icons go here
  );
}

registerIcons();
