// import the library
import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faCode,
  faHighlighter,
  faTools,
  faHome,
  faPowerOff,
  faQuestion,
  faQuestionCircle,
  faUsers,
  faFolder,
  faBuilding,
  faUserTie,
  faUserCircle,
  faTasks,
  faAngleUp,
  faAngleDown,
  faArrowRight,
  faArrowLeft,
  faLongArrowAltLeft,
  faLongArrowAltRight,
  faSearch,
  faPhone,
  faPhoneAlt,
  faPhoneSquare,
  faEdit,
  faTrash,
  faMapMarkerAlt,
  faTh,
  faList,
} from "@fortawesome/free-solid-svg-icons";

import { faQuestionCircle as faQuestionCircleRegular } from "@fortawesome/free-regular-svg-icons";

library.add(
  faCode,
  faHighlighter,
  faTools,
  faHome,
  faPowerOff,
  faQuestion,
  faQuestionCircle,
  faQuestionCircleRegular,
  faUsers,
  faUserCircle,
  faFolder,
  faBuilding,
  faUserTie,
  faTasks,
  faAngleUp,
  faAngleDown,
  faArrowRight,
  faArrowLeft,
  faLongArrowAltLeft,
  faLongArrowAltRight,
  faSearch,
  faPhone,
  faPhoneAlt,
  faPhoneSquare,
  faEdit,
  faTrash,
  faMapMarkerAlt,
  faPhoneAlt,
  faTh,
  faList

  // more icons go here
);
